const vocabulario = [
  // UNIDAD 1
  [
    'ANO HITO: あの　ひと (aquella persona)',
    'HITO: (persona (familiar))',
    'KATA: (persona (formal))',
    'TANAKA SAN:',
    'SENSEI: (maestro, profesor)',
    'GAKUSEI: (alumno)',
    'KAISHAIN: (empleado de empresa)',
    '~ NO SHAIN: (empleado de ~)',
    '~ CHAN: (sufijo de niña)',
    '~ KUN: (sufijo de niño)',
    '~ JIN: (sufijo de nacionalidad)',
    'GINKOUIN: (funcionario de banco)',
    'ISHA: (medico)',
    'KENKYUUSHA: (investigador)',
    'ENGINIA: (ingeniero)',
    'DAIGAKU: (universidad)',
    'BYOUIN: (hospital)',
    'DENKI: (luz, electricidad)',
    'DARE: (quien (familiar))',
    'DONATA: (quien (formal))',
    '~ SAI: (~ años)',
    'NANSAI: (cuantos años? (familiar))',
    'OIKUTSU: (cuantos años? (formal))',
    'HAI: (si)',
    'IIE: (no)',
    'SHITSUREI DESU GA ~: (disculpe, pero ~)',
    'HAJIMEMASHITE: (mucho gusto)',
    'DOUZO YOROSHIKU: (encantado)',
    'KOCHIRA HA ~ SAN DESU: (le presento ~ san)',
    '~ KARA KIMASHITA: (soy de ~)',
    'AMERIKA: (EEUU)',
    'IGIRISU: (inglatera)',
    'KANKOKU: (corea del sur)',
    'NIHON: (japón)',
    'FURANSU: (francia)',
    'CHUUGOKU: (china)'
  ],
  // UNIDAD 2
  [
    'KORE: (éste/ésta/esto con objetos)',
    'SORE: (ése/ésa/eso con objetos)',
    'ARE: (aquél/aquélla/aquello con objetos)',
    'KONO ~: (este/esta ~)',
    'SONO ~: (ese/esa ~)',
    'ANO ~: (aquel/aquella ~)',
    'HON: (libro)',
    'JISHO: (diccionario)',
    'ZASHI: (revista)',
    'SHINBUN: (diario)',
    'NOOTO: (cuaderno de notas)',
    'TECHOUU: (agenda)',
    'MEISHI: (tarjeta de visita)',
    'KAADO: (tarjeta)',
    'TEREHON KAADO: (tarjeta de telefono)',
    'ENPITSU: (lápiz)',
    'BORUPEN: (virome)',
    'SHAPUPENSHIRU: (portaminas)',
    'KAGI: (llave)',
    'TOKEI: (reloj)',
    'KASA: (paraguas)',
    'KABAN: (valija, bolsa)',
    'TEREBI: (televisión)',
    'RAJIO: (radio)',
    'KAMERA: (cámara)',
    'JIDOUSHA/KURUMA: (auto)',
    'KONPYUUTA: (computadora)',
    'TSUKUE: (escritorio)',
    'ISU: (silla)',
    'TEBURU: (mesa)',
    'CHOKOREETO: (chocolate)',
    'KOOHII: (café)',
    'EIGO: (idioma inglés)',
    'NIHONGO: (idioma japonés)',
    '~ GO: (~ idioma)',
    'NAN: (qué)',
    'SOU DESU: (así es)',
    'CHIGAIMASU: (no, no es así)',
    'SOU DESU KA?: (ah, si?)',
    'ANOU: (esto...)',
    'HON NO KIMOCHI DESU: (Es un obsequio modesto)',
    'DOUZO: (Aqui tiene/sirvase)',
    'DOUMO: (gracias (formal))',
    'KOREKARA OSEWANI NARIMASU: (A partir de ahora voy a ser una molestia)',
    'KOCHIRAKOZO YOROSHIKU: (yo tambien estoy encantado de conocerlo)'
  ],
  // UNIDAD 3
  [
    'KOKO: (aquí/acá/este lugar)',
    'SOKO: (ahí/ese lugar)',
    'ASOKO: (aquel lugar)',
    'DOKO: (donde, quel lugar?)',
    'KOCHIRA: (por aquí/este lugar)',
    'SOCHIRA: (por ahí/ese lugar)',
    'ACHIRA: (por allí/aquel lugar)',
    'DOCHIRA: (por dónde?)',
    'KYOUSHITSU: (aula)',
    'SHOKUDOU: (comedor)',
    'JIMUSHOU: (oficina)',
    'KAIGISHITSU: (sala de reunión)',
    'UKETSUKE: (recepción)',
    'ROOBI: (lobby)',
    'HEYA: (habitación/pieza)',
    'TOIRE/OTEARAI: (baños)',
    'KAIDAN: (escalera)',
    'EREBEETA: (ascensor)',
    'ESUKAREETAA: (escalera mécanica)',
    'O KUNI: (país)',
    'KAISHA: (empresa)',
    'UCHI: (casa)',
    'DENWA: (telefono)',
    'KUTSU: (zapatos)',
    'NEKUTAI: (corbata)',
    'WAIN: (vino)',
    'TABAKO: (cigarillo)',
    'URIBA: (sección de almacén)',
    'CHIKA: (sótano)',
    '~ KAI: (~ nro piso)',
    'NANGAI: (qué piso?)',
    '~ EN: (~ yenes)',
    'IKURA: (cuanto? (cantidad numerica))',
    'SUMIMASEN: (disculpe)',
    '~ DE GOZAIMASU: (~ DESU (formal))',
    '~ WO MISETE KUDASAI: (muéstreme ~ por favor)',
    '~ WO KUDASAI: (deme ~ por favor)',
    'ITARIA: (italia)',
    'SUISU: (suiza)'
  ],
  // UNIDAD 4
  [
    'DEPAATO: (centro comercial/mall)',
    'GINKOU: (banco)',
    'YOUBINKYOUKU: (oficina de correo)',
    'TOSHOKAN: (biblioteca)',
    'BIJUTSUKAN: (museo de arte)',
    'IMA: (ahora)',
    '~ JI: (las ~ horas)',
    '~ FUN/PUN: (~ minutos)',
    'ROKU JI HAN: (las 6 y media)',
    'NANJI: (qué hora?)',
    'NANPUN: (qué minuto?)',
    'GOZEN: (de la mañana)',
    'GOGO: (de la tarde)',
    'ASA: (la mañana)',
    'HIRU: (el mediodia)',
    'BAN/YORU: (noche)',
    'OTOTOI: (anteayer)',
    'KINOU: (ayer)',
    'KYOU: (hoy)',
    'ASHITA: (mañana)',
    'ASATE: (pasado mañana)',
    'KESA: (esta mañana)',
    'KONBAN: (esta noche)',
    'YASUMI: (el descanso, pausa)',
    'MAIASA: (todas las mañanas)',
    'MAIBAN: (todas las noches)',
    'MAINICHI: (todos los dias)',
    'GETSUYOUBI: (lunes)',
    'KAYOUBI: (martes)',
    'SUIYOUBI: (miercoles)',
    'MOKUYOUBI: (jueves)',
    'KINYOUBI: (viernes)',
    'DOYOUBI: (sábado)',
    'NICHIYOUBI: (domingo)',
    'NANYOUBI: (qué dia de la semana?)',
    'BANGOU: (número)',
    'NANBAN: (qué número?)',
    '~ KARA ~: (~ desde ~)',
    '~ MADE ~: (~ hasta ~)',
    '~ TO ~: (~ y ~)',
    'TAIHEN DESUNE: (como le cuesta!)',
    'EETO...: (bueno...)',
    'ONEGAI SHIMASU: (por favor)',
    'KASHI KOMARI MASHITA: (bien, entendido)'
  ],
  // UNIDAD 5
  [
    'GAKOU: (escuela)',
    'SUUPAA: (supermercado)',
    'EKI: (estación de trenes)',
    'HIKOUKI: (avión)',
    'FUNE: (barco)',
    'DENSHA: (trén electrico)',
    'CHIKATETSU: (subte)',
    'SHINKANSEN: (tren alta velocidad)',
    'BASU: (colectivo)',
    'TAKUSHI: (taxi)',
    'JITENSHA: (bicicleta)',
    'ARU ITE: (voy a pie)',
    'TOMODACHI: (amigo)',
    'KARE: (él/el novio)',
    'KANOJO: (ella/la novia)',
    'KAZOKU: (familia)',
    'HITORI DE: (estando solo)',
    'SENSHUU: (la semana pasada)',
    'KONSHUU: (esta semana)',
    'RAISHUU: (la semana que viene)',
    'SENGETSU: (el més pasado)',
    'KONGETSU: (este més)',
    'RAIGETSU: (el més que viene)',
    'KYONEN: (el año pasado)',
    'KOTOSHI: (este año)',
    'RAINEN: (el año que viene)',
    '~ GATSU: (~ mes)',
    'NANGASTU: (qué mes?)',
    'TSUITACHI: (1er día del mes)',
    'FUTSUKA: (2ndo día del mes/2 días)',
    'MIKA: (3er día del mes/3 días)',
    'YOKA: (4to día del mes/4 días)',
    'ITSUKA: (5to día del mes/5 días)',
    'MUIKA: (6to día del mes/6 días)',
    'NANOKA: (7mo día del mes/7 días)',
    'YOUKA: (8vo día del mes/8 días)',
    'KOKONOKA: (9no día del mes/9 días)',
    'TOOKA: (día 10 del mes/10 días)',
    'JUUYOKA: (día 14 del mes/14 días)',
    'HATSUKA: (día 20 del mes/ 20 días)',
    'NIJUUYOKA: (día 24 del mes/ 24 días)',
    '~ NICHI: (~ dia del mes/ ~ dias)',
    'NANICHI: (cuantos dias?/qué dia del mes?)',
    'ITSU: (cuando?)',
    'ITSUMO: (siempre)',
    'TANJOUBI: (el cumpleaños)',
    'TSUGI NO ~: (el proximo ~)',
    'DOU ITASHIMASHITA: (de nada)'
  ],
  // UNIDAD 6
  [
    'GOHAN: (arroz/comida)',
    'ASAGOHAN: (desayuno)',
    'HIRUGOHAN: (almuerzo)',
    'BANGOHAN: (cena)',
    'PAN: (pan)',
    'TAMAGO: (huevo)',
    'NIKU: (carne)',
    'SAKANA: (pescado)',
    'YASAI: (verdura)',
    'KUDAMONO: (fruta)',
    'MISU: (agua)',
    'OCHA: (té verde)',
    'KOUCHA: (té negro)',
    'GYUNYU/MIRUKU: (leche)',
    'JUUSU: (jugo)',
    'BIRU: (cerveza)',
    'OSAKE: (bebida alcohólica)',
    'BIDEO: (video)',
    'EIGA: (pelicula)',
    'SHIDI: (el CD)',
    'TEGAMI: (carta/correspondencia)',
    'REPOTO: (informe/reporte)',
    'SHASHIN: (fotografía)',
    'MISE: (tienda/negocio)',
    'RESUTORAN: (restaurante)',
    'NIWA: (jardín)',
    'SHUKUDAI: (deberes/tareas)',
    'TENISU: (ténis)',
    'SAKA: (futból)',
    'HANAMI: (floración de los cerezos)',
    'ISHONI: (juntos)',
    'CHOTO: (un poco)',
    'TOKIDOKI: (de vez en cuando)',
    'SOREKARA: (y después)',
    'II DESUNE: (buena idea!)',
    'WAKARIMASHITA: (entendido)',
    'NANDESUKA?: (qué deseaba?)'
  ],
  // UNIDAD 7
  [
    'TE: (mano/brazos)',
    'HASHI: (palillos)',
    'SPUUN: (cuchara)',
    'NAIFU: (cuchillo)',
    'FOOKU: (tenedor)',
    'HASAMI: (tijeras)',
    'FAKUSU: (FAX)',
    'PASOKON: (la PC)',
    'PANCHI: (perforador de hojas)',
    'HO CHIKISU: (abrochadora)',
    'SEROTEEPU: (cinta adhesiva)',
    'KESHIGOMU: (goma de borrar)',
    'KAMI: (papel)',
    'HANA: (flor)',
    'SHATSU: (camiseta)',
    'PUREZENTO: (regalo)',
    'NIMOTSU: (equipaje/paquete)',
    'OKANE: (dinero)',
    'KIPU: (pasaje/boleto)',
    'KERISUMASU: (navidad)',
    'CHICHI: (mi padre)',
    'HAHA: (mi madre)',
    'OTOUSAN: (padre de otro)',
    'OKAASAN: (madre de otro)',
    'MOU: (ya)',
    'MADA: (todavia)',
    'KOREKARA: (desde ahora)',
    'SUTEKI DESU NE!: (qué bonito!)',
    'GOMEN KUDASAI: (disculpa, por favor (cuando se entra a una casa))',
    'IRA SHAI: (bienvenido)',
    'DOUZO OAGARI KUDASAI: (pase por favor)',
    'SHITSUREI SHIMASU: (con su permiso)',
    '~ HA IKAGA DESU KA?: (~ le apetece?)',
    'ITADAKIMASU: (se usa cuando se recibe comida o algo)',
    'RYOKOU: (viaje)',
    'OMIYAGE: (suvenir de viaje)',
    'YOOROPA: (europa)',
    'SUPEIN: (españa)'
  ]
];
